stages:
  - first
  - second
  - third

print_text:
  stage: first
  tags:
    - build
  only:
    - dev
  script:
    - echo "Hello World first!"


print_second:
  stage: second
  tags:
    - build
  only:
    - dev
  script:
    - echo "Hello World second!"


print_third:
  stage: third
  tags:
    - build
  only:
    - dev
  script:
    - echo "Hello World third!"
